# Generated by Django 3.2.7 on 2022-10-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystatistics',
            name='date',
            field=models.DateField(max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadimagetest',
            name='time',
            field=models.TimeField(default='03:28:36'),
        ),
    ]
